name: Cleanup PR Preview

on:
  pull_request:
    types: [closed]

permissions:
  contents: write

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout gh-pages branch
        uses: actions/checkout@v4
        with:
          ref: gh-pages

      - name: Remove PR preview directory
        run: |
          if [ -d "pr-preview/pr-${{ github.event.pull_request.number }}" ]; then
            git config user.name github-actions[bot]
            git config user.email github-actions[bot]@users.noreply.github.com
            git rm -rf pr-preview/pr-${{ github.event.pull_request.number }}
            git commit -m "Remove preview for PR #${{ github.event.pull_request.number }}"
            git push
            echo "✅ Removed preview directory for PR #${{ github.event.pull_request.number }}"
          else
            echo "ℹ️ No preview directory found for PR #${{ github.event.pull_request.number }}"
          fi
