name: Deploy PR Preview

on:
  pull_request:
    types: [opened, synchronize, reopened]

# GitHub Pagesへのデプロイ権限を設定
permissions:
  contents: write
  pull-requests: write

# 同時実行を制御（PR番号ごとに管理）
concurrency:
  group: "pages-pr-${{ github.event.pull_request.number }}"
  cancel-in-progress: true

jobs:
  deploy-preview:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 8

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm run build
        env:
          VITE_BASE_URL: /codex-test_tic-tac-toe/pr-preview/pr-${{ github.event.pull_request.number }}/

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./dist
          destination_dir: pr-preview/pr-${{ github.event.pull_request.number }}
          keep_files: true
          force_orphan: false

      - name: Comment PR with preview URL
        uses: actions/github-script@v7
        with:
          script: |
            const previewUrl = `https://${{ github.repository_owner }}.github.io/codex-test_tic-tac-toe/pr-preview/pr-${{ github.event.pull_request.number }}/`;
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `## 🚀 プレビューデプロイ完了\n\nプレビューURL: ${previewUrl}\n\n> このプレビューはPRがクローズされると自動的に削除されます。`
            });
