name: Deploy PR Preview

on:
  pull_request:
    types: [opened, synchronize, reopened]

# GitHub Pagesへのデプロイ権限を設定
permissions:
  contents: read
  pages: write
  id-token: write
  pull-requests: write

# 同時実行を制御（PR番号ごとに管理）
concurrency:
  group: "pages-pr-${{ github.event.pull_request.number }}"
  cancel-in-progress: true

jobs:
  build-preview:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 8

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Build for PR preview
        run: pnpm run build
        env:
          VITE_BASE_PATH: /Codex_tictactoe/pr-preview/pr-${{ github.event.pull_request.number }}/

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist

  deploy-preview:
    environment:
      name: github-pages
      url: https://${{ github.repository_owner }}.github.io/Codex_tictactoe/pr-preview/pr-${{ github.event.pull_request.number }}/
    runs-on: ubuntu-latest
    needs: build-preview
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

      - name: Comment PR with preview URL
        uses: actions/github-script@v7
        with:
          script: |
            const previewUrl = `https://${{ github.repository_owner }}.github.io/Codex_tictactoe/pr-preview/pr-${{ github.event.pull_request.number }}/`;
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `## 🚀 プレビューデプロイ完了\n\nプレビューURL: ${previewUrl}\n\n> このプレビューはPRがクローズされると自動的に削除されます。`
            });
